[package]
name = "tower-sessions-mongodb-store"
description = "MongoDB session store for `tower-sessions`."
version = "0.11.0"
edition = "2021"
authors = ["Max Countryman <hello@maxcountryman.com>"]
license = "MIT"
homepage = "https://github.com/maxcountryman/tower-sessions-stores"
keywords = ["axum", "sessions", "cookie", "tower", "mongodb"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/maxcountryman/tower-sessions-stores"
documentation = "https://docs.rs/tower-sessions-mongodb-store"
readme = "README.md"

[dependencies]
async-trait = "0.1.89"
bson = { version = "3.1.0", features = ["time-0_3"] }
mongodb = { version = "3.7.0" }
rmp-serde = "1.3.1"
serde = "1.0.228"
thiserror = "2.0.18"
time = "0.3.47"
tower-sessions-core = { version = "0.15.0", features = ["deletion-task"] }

[dev-dependencies]
axum = "0.8.9"
tower-sessions = "0.15.0"
tokio = { version = "1.52.3", features = ["full"] }
tokio-test = "0.4.5"
serde = "1"

[[example]]
name = "mongodb"
